### ISSUE TITLE
WIFI basic HTTP Client  #if with no expression 

### ISSUE THREAD

**Issue by sallah21** [m5stack/M5CoreS3#45]
I got got compilation error for WIFI basic HTTPClient example
Local\Arduino15\packages\esp32\hardware\esp32\2.0.11/tools/sdk/esp32c3/include/hal/include/hal/i2c_types.h:85:28: error: #if with no expression
 #if CONFIG_IDF_TARGET_ESP32

**Comment by sallah21** [comment]
examples/Advanced/WIFI/BasicHttpClient/BasicHttpClient.ino

**Comment by Tinyu-Zhao** [comment]
<img width="1030" alt="image" src="https://github.com/m5stack/M5CoreS3/assets/44396641/ae75e054-76e2-4d10-8a78-fef55b5c2d59">
The following compilation configuration failed to reproduce, please specify the compilation environment you are using and the libraries and board definitions you are using.
[env:M5CoreS3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = /dev/cu.usbmodem144101
upload_speed = 1500000
monitor_speed = 115200
monitor_port = /dev/cu.usbmodem144101
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=4

**Comment by Resonious** [comment]
I'm getting this too, with just the Core S3 "hello world" program:

```c++
#include <M5CoreS3.h>

void setup() {
    M5.begin(true, true, false); 
    M5.Lcd.setTextSize(2);
    M5.Lcd.setCursor(100, 120);
    M5.Lcd.print("Hello World");
}

void loop() {
    USBSerial.println("Hello World");
    delay(500);
}
```

**Comment by Tinyu-Zhao** [comment]
> I'm getting this too, with just the Core S3 "hello world" program:
> 
> 
> 
> ```c++
> 
> #include <M5CoreS3.h>
> 
> 
> 
> void setup() {
> 
>     M5.begin(true, true, false); 
> 
>     M5.Lcd.setTextSize(2);
> 
>     M5.Lcd.setCursor(100, 120);
> 
>     M5.Lcd.print("Hello World");
> 
> }
> 
> 
> 
> void loop() {
> 
>     USBSerial.println("Hello World");
> 
>     delay(500);
> 
> }
> 
> ```

Please post the program or the address of the program

**Comment by Resonious** [comment]
Sorry, probably a rookie mistake. I just grabbed `arduino-cli` and ran

```
arduino-cli core install esp32:esp32
arduino-cli lib install M5CoreS3
```

My `~/.arduino15/arduino-cli.yaml` looks like

```
board_manager:
  additional_urls: 
    - https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/arduino/package_m5stack_index.json
build_cache:
  compilations_before_purge: 10
  ttl: 720h0m0s
daemon:
  port: "50051"
directories:
  data: /home/nigel/.arduino15
  downloads: /home/nigel/.arduino15/staging
  user: /home/nigel/Arduino
library:
  enable_unsafe_install: false
logging:
  file: ""
  format: text
  level: info
metrics:
  addr: :9090
  enabled: true
output:
  no_color: false
sketch:
  always_export_binaries: false
updater:
  enable_notification: true
```

and I've run `arduino-cli core update-index`. I'm guessing there's something else I need to do, but I'm not sure what it is.
